name: Release

permissions:
  contents: write

on:
  workflow_call:
    outputs:
      devops_approval_time:
        description: DevOps approval time
        value: ${{ jobs.devops-approval.outputs.APPROVAL_TIMESTAMP }}
      qa_approval_time:
        description: QA approval time
        value: ${{ jobs.qa-approval.outputs.APPROVAL_TIMESTAMP }}

jobs:
  devops-approval:
    runs-on: ubuntu-latest
    environment: ${{ inputs.devops_approval_environment }}
    steps:
      - name: DevOps approval
        id: approval
        run: |
          echo "Deploy on peak traffic period has been approved by DevOps."
          echo "APPROVAL_TIMESTAMP=$(date +%s)" >> $GITHUB_OUTPUT
    outputs:
      APPROVAL_TIMESTAMP: ${{ steps.approval.outputs.APPROVAL_TIMESTAMP }
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
